#This YAML file defines a Docker Compose service for the API. It does the following:

#Specifies the auditapi service, which is built from the current directory using the Dockerfile.

#Maps port 8080 from the container to port 8080 on the host machine.

#Specifies an environment file (.env) to load environment variables.

#Defines a volume to store MongoDB data

version: '3'
services:
  # The API uses the Flask framework to receive and manage GET and POST requests
  auditapi:
    build:
      context: .  # Context points to the directory containing your application code
      dockerfile: Dockerfile  # Dockerfile for building the API service
    ports:
      - 8080:8080
    env_file:   
      - .env
    volumes:
      - .env:/app/.env  # This will map the .env file from the host to the /app directory inside the container
  